encoder:
  params:
      adaptive_type: [AdaptiveAvgPool2d, AdaptiveMaxPool2d]
      conv_out_size: [4, 8, 16]
env: [walker_walk, reacher_easy, finger_spin, cheetah_run, ball_in_cup_catch, cartpole_swingup]
