# ALL Configs here must exist in the hydra "config.yaml"

seed: 0 # use 0 so it will be overiden by 1+ run_id
log_save_tb: false
save_video: false

# NEW LOGS
log_save_wandb: false
replay_buffer_augmentation: True

encoder:
  class: encoders.AdaptiveConvOut
  params:
      obs_shape: ${agent.params.obs_shape}
      feature_dim: 50
      adaptive_type: AdaptiveMaxPool2d
      conv_out_size: 1
